### ISSUE TITLE
Traffic not forwarding

### ISSUE THREAD

**Issue by mmanoj** [REANNZ/ruru#1]
Hi @czivar ,

I try to use ruru latency monitor as forward bridge with physical nic, it's start up but not forwarding traffic to other port.

following command I use:
dpdk-latency -c 3 -n 4 -- -p 3 -T 60 --config "(0,0,1)" --forwarding

Note: No errors and no statistics.

Please advice.

Thank you,
Manoj M

**Comment by mmanoj** [comment]
I have physical DPDK supported 1Gbps x 2 port NIC

**Comment by mmanoj** [comment]
Hi,

please help me to run as forwarder with physical nic having 4 queues Tx and Rx each and cpu with 4 cors

Thanks in advance

**Comment by czivar** [comment]
Hi @mmanoj ,

In order to have the forwarding option enabled, you will have to use two ports and in --config you will have to configure both ports. It should be something like --config "(0,0,1),(1,0,2)" .

**Comment by mmanoj** [comment]
hi @czivar 

Thank you for the advice, I will test and update you.

**Comment by mmanoj** [comment]
Hi @czivar 

I try with below options but not forwarding traffic port 0->1 & 1->0 . I will email you by connectivity diagram with desktop switch.

PC --> desktop switch, switch main port --> DPDK port 2, DPDK port 1 --> internet router.

**Comment by mmanoj** [comment]
root@infinity:/opt/ruru/dpdk-latency/build# ./dpdk-latency -l 1,2 -n 4 -- -p 0x3 -T 60 --config "(0,0,1),(1,0,2)" --forwarding
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:19.0 on NUMA socket -1
EAL:   probe driver: 8086:153b net_e1000_em
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10a7 net_e1000_igb
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10a7 net_e1000_igb
Initializing port 0 ... 
Initializing port 1 ... 
Setting up hash table for lcore 2, on socket 0
setting up rx queue on port 0, queue 0
setting up rx queue on port 1, queue 0
done: 
done: 

Checking link status......................done
Port 0 Link Up - speed 1000 Mbps - full-duplex
Port 1 Link Up - speed 100 Mbps - full-duplex

**Comment by mmanoj** [comment]
if I try with skeleton app PC get connected and getting DHCP and able to browse inyternet, however with your app same not happening. Your advice really appreciated.
